name: ap_admin_portal
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.17.0
  shared_preferences:
  uuid:
  image:
  path_provider:
  share:
  url_launcher:
  image_picker:
  permission_handler:
  pull_to_refresh:
  wakelock:
  system_settings:
  intl_utils: ^2.1.0
  hive: ^2.2.3
  hive_flutter:
  firebase_messaging: ^14.2.1
  #flutter_local_notifications:
  lottie: ^2.1.0
  email_validator: ^2.1.17
  dio_cache_interceptor:
  dio:
  firebase_core:
  cloud_firestore:
  shimmer:
  firebase_remote_config:
  firebase_analytics:
  firebase_storage:
  jwt_decoder: ^2.0.1
  encrypt:
  stream_transform:
  badges: ^2.0.3
  package_info_plus: ^3.0.2
  dartz:
  get_it:
  injectable:
  retry:
  firebase_crashlytics: ^3.0.9
  dropdown_button2: ^1.9.4
  flutter_jailbreak_detection:
  provider:
  syncfusion_flutter_sliders: ^20.4.42
  internet_connection_checker_plus: ^1.0.1
  cached_network_image:
  flutter_svg:
  flutter_staggered_animations:
  logger:
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  envied: ^0.3.0
  animated_text_kit: ^4.2.2
  flutter_gen: ^5.1.0+1
  #custom_line_indicator_bottom_navbar: ^0.0.8
  font_awesome_flutter: ^10.3.0
  flutter_image_compress: ^1.1.3
  flutter_datetime_picker: ^1.5.1
  flutter_typeahead: ^4.1.1
  share_plus: ^6.3.0
  auto_size_text: ^3.0.0
  equatable:
  dotted_border:
  image_cropper: ^3.0.1
  flutter_expandable_fab: ^1.7.0
  expandable_fab_menu: ^0.0.1
  flutter_animate: ^1.0.0
  flutter_cache_manager: ^3.3.0
  from_css_color: ^2.0.0
  google_fonts: ^3.0.1
  json_path: ^0.4.1
  page_transition: ^2.0.4
  sqflite: ^2.2.0+2
  timeago: ^3.2.2
  sidebarx: ^0.14.0
  data_table_2: ^2.3.10
  fl_chart: ^0.61.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
  injectable_generator:
  flutter_gen_runner:
  envied_generator:

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

flutter_intl:
  enabled: true
